name: release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install modules
        run: |
          npm install -D semantic-release @semantic-release/git @semantic-release/github

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
            skip-check: CKV2_AWS_41,CKV2_GHA_1
            output_format: cli,sarif
            output_file_path: console,results.sarif   

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}