name: terraform build

on:
  push:

jobs:
  terraform:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ec2
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.CI_ROLE }}

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: format
        run: terraform fmt -recursive
        
      - name: plan
        run: terraform plan